AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to create a DynamoDB Global Table | ka-me-ha-me-ha-archives

Parameters:
  GlobalTableName:
    Type: String
    Default: ka-me-ha-me-ha-archives
    Description: Name of the Global table to create

  Region1:
    Type: String
    Default: us-west-2
    Description: The first region for the replica

  Region2:
    Type: String
    Default: ap-south-1
    Description: The second region for the replica

Resources:
  KamehamehaArchivesTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: !Ref GlobalTableName
      AttributeDefinitions: 
        - AttributeName: User_id
          AttributeType: S
        - AttributeName: Game_id
          AttributeType: S
        - AttributeName: User_name
          AttributeType: S
        - AttributeName: User_age
          AttributeType: N
      KeySchema:
        - AttributeName: User_id
          KeyType: HASH
        - AttributeName: Game_id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: User_id
              KeyType: HASH
            - AttributeName: User_name
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: AgeIndex
          KeySchema:
            - AttributeName: User_id
              KeyType: HASH
            - AttributeName: User_age
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
                
      Replicas:
        - Region: !Ref Region1
          ReadProvisionedThroughputSettings:
            ReadCapacityAutoScalingSettings:
              MinCapacity: 1
              MaxCapacity: 5
              TargetTrackingScalingPolicyConfiguration:
                TargetValue: 70
          TableClass: STANDARD
          Tags:
            - Key: Environment
              Value: Dev
            - Key: Project
              Value: Task-1

        - Region: !Ref Region2
          ReadProvisionedThroughputSettings:
            ReadCapacityAutoScalingSettings:
              MinCapacity: 1
              MaxCapacity: 5
              TargetTrackingScalingPolicyConfiguration:
                TargetValue: 70
          TableClass: STANDARD
          Tags:
            - Key: Environment
              Value: Dev
            - Key: Project
              Value: Task-1

      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

      WriteProvisionedThroughputSettings:
        WriteCapacityAutoScalingSettings:
          MinCapacity: 4
          MaxCapacity: 10
          TargetTrackingScalingPolicyConfiguration:
            TargetValue: 70

Outputs:
  GlobalTableStreamArn:
    Description: The ARN of the Global Table
    Value: !GetAtt KamehamehaArchivesTable.StreamArn
    Export:
      Name: GlobalTableStreamArn
