AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to create an S3 bucket

Parameters:
  BucketName:
    Type: String
    Default: ka-me-ha-me-ha
    Description: Name of the S3 bucket to create

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: Dev
        - Key: Project
          Value: Task-1

Outputs:
  BucketRef:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket